FROM aswf/ci-common


ENV PRMAN_VERSION=23.4 
ENV RMANTREE="/opt/pixar/RenderManProServer-23.4"
ENV RFHTREE="/opt/pixar/RenderManForHoudini-23.4"
ENV PATH=$PATH:$RMANTREE/bin
ENV RMAN_PROCEDURALPATH=$RFHTREE/18.0.499/openvdb:&


ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:opt/pixar/RenderManProServer-23.4/lib


